---
- hosts: db
  become: true
  tasks: 
  - name: "install mysql-server"
    apt: name=mysql-server update_cache=yes state=present
  - name: "install python-mysqldb"
    apt: name=python-mysqldb update_cache=no state=present
  - name: "Restart mysql server"
    service:
      name: mysql
      state: restarted

  - name: "Allow binding from other servers"
    lineinfile:
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
      regexp: ^bind-address
      line: "bind-address = 0.0.0.0"

  - name: "Restart mysql server"
    service:
      name: mysql
      state: restarted

  - name: "Create database"
    mysql_db: name=demodb state=present

  - name: "Create user"
    mysql_user: name=demo password=demo priv=demodb.*:ALL host='%' state=present
#  - name: "Copy sql"
#    copy:
#      src: "/tmp/projectcode/db/createtable.sql"
#      dest: "/tmp/"

#  - name: "Create seed data"
#    shell: "mysql -udemo -pdemo < /tmp/createtable.sql"
#  - name: "Use mysql_db to create seed data"
#    mysql_db:
#      login_user: demo
#      login_password: demo
#      name: demodb
#      state: import
#      target: /tmp/createtable.sql

