- hosts: all
  gather_facts: yes
  vars:
    varone: Hello
    run_env: dev
  vars_files:
  - vars.yml
  - "{{run_env}}.yml"
  - "{{ansible_os_family}}.yml"
  - ["{{ansible_nodename}}.yml", "default.yml"]
  tasks:
  - debug:
      msg: "{{varone}}"
  - debug:
      var: port_value
  - debug:
      var: node_specific
  #- package:
  #    name: "{{webpackage}}" 
