- hosts: localhost
  gather_facts: no
  vars_files:
  - secret_keys.yml
  - vars.yml
  tasks:
  - debug:
      msg: "This is the secret password {{dbpass}}"
  - debug:
      msg: "This is the secret password {{license_key}}"
