- name: "update cache"
  apt:
    update_cache: yes
    cache_valid_time: "{{cache_valid_time}}"
    #cache_valid_time: "{{cache_valid_time | int }}"
- name: "install packages"
  apt:
    name: item
    update_cache: no
  with_items:
    "{{packages}}"
  notify: "restart apache2" 
- name: "start and enable apache2"
  service:
    name: apache2
    enabled: no
    state: started
- name: "Port change"
  lineinfile:
    dest: "/etc/apache2/ports.conf"
    regexp: "^Listen"    
    line: "Listen {{apache_port}}"
  notify: 
    - "restart apache2"
